### ISSUE TITLE
Add nrRegion parameter to doc

### ISSUE THREAD

**Issue by k0rn1** [newrelic/serverless-newrelic-lambda-layers#112]
Hi there 👋

Today I have tried to use this plugin but it always failed while deploying with the following error:

`Unexpected token < in JSON at position 0`

After looking through the code I have noticed that the default api endpoint points to  `https://api.newrelic.com/graphql`.
As a user in the EU 🇪🇺️, I had to add `nrRegion: 'eu'` to my `serverless.yml` to point the endpoint to` https://api.eu.newrelic.com/graphql`.

Either I have missed this or it is missing in the documentation (README).
If the second one is the case also consider adding it to the Setup AWS Lambda monitoring code snippet.

**Comment by kolanos** [comment]
@k0rn1 Thanks for reporting this, looks like it was addressed.
