### ISSUE TITLE
HTTP error 500 when installing the plugin

### ISSUE THREAD

**Issue by BaptisteKaliop** [newrelic/serverless-newrelic-lambda-layers#120]
Hi,

I'm trying to install the lambda layer to my serverless account.

Since I added the entry 'serverless-newrelic-lambda-layers' to my plugins list, it seems that there is a http call that is triggered that result in a HTTP error 500 in the sls deploy : 

> Status Code Error --------------------------------------
>  
>   StatusCodeError: 500 - "{\"Code\":\"InternalServerError\",\"Message\":\"An internal server error occurred.\"}"
>       at new StatusCodeError (/home/baptiste/www/neurodiem/node_modules/request-promise-core/lib/errors.js:32:15)
>       at Request.plumbing.callback (/home/baptiste/www/neurodiem/node_modules/request-promise-core/lib/plumbing.js:104:33)
>       at Request.RP$callback [as _callback] (/home/baptiste/www/neurodiem/node_modules/request-promise-core/lib/plumbing.js:46:31)
>       at Request.self.callback (/home/baptiste/www/neurodiem/node_modules/request/request.js:185:22)
>       at Request.emit (events.js:314:20)
>       at Request.EventEmitter.emit (domain.js:483:12)
>       at Request.<anonymous> (/home/baptiste/www/neurodiem/node_modules/request/request.js:1154:10)
>       at Request.emit (events.js:314:20)
>       at Request.EventEmitter.emit (domain.js:483:12)
>       at IncomingMessage.<anonymous> (/home/baptiste/www/neurodiem/node_modules/request/request.js:1076:12)
>       at Object.onceWrapper (events.js:420:28)
>       at IncomingMessage.emit (events.js:326:22)
>       at IncomingMessage.EventEmitter.emit (domain.js:483:12)
>       at endReadableNT (_stream_readable.js:1241:12)
>       at processTicksAndRejections (internal/process/task_queues.js:84:21)

It happens after all these : 

> Serverless: Adding NewRelic layer to trapError
> Serverless: Adding NewRelic layer to ...
> Serverless: Adding NewRelic layer to assetLinks

I properly added the configuration inside my custom entry in serverless.yml

```
newRelic:
    accountId: 'xxxxxxx'
    apiKey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    nrRegion: 'eu'
    debug: true
```
This error is not raised if I remove the plugin from my list of plugins.
Here is my list of plugins : 

```
plugins:
  - serverless-api-gateway-caching
  - serverless-layers
  - serverless-offline # run offline lambdas
  - serverless-offline-scheduler
  - serverless-offline-sqs
  - serverless-plugin-tracing # activate xray on lambdas
  - serverless-plugin-split-stacks
  - serverless-plugin-warmup
  - serverless-prune-plugin
  - serverless-s3-sync # sync a folder with an s3 bucket
  - serverless-newrelic-lambda-layers
```
  
  Adding a SLS_DEBUG=* did not help.
  
  Any ideas on how to fix that?

**Comment by BaptisteKaliop** [comment]
Looks like the error comes from 

```
return request(`https://${this.region}.layers.newrelic-external.com/get-layers?CompatibleRuntime=${runtime}`).then(response => {
                const awsResp = JSON.parse(response);
                return _.get(awsResp, "Layers[0].LatestMatchingVersion.LayerVersionArn");
            })
```

in the method getLayerArn with URI : `https://eu-west-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=nodejs12.x`

**Comment by kolanos** [comment]
@BaptisteKaliop Thanks for reporting. I just ran the following:

```
curl https://eu-west-1.layers.newrelic-external.com/get-layers?CompatibleRuntime=nodejs12.x
```

And got:

```
{"Layers":[{"LayerName":"NewRelicNodeJS12X","LayerArn":"arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS12X","LatestMatchingVersion":{"LayerVersionArn":"arn:aws:lambda:eu-west-1:451483290750:layer:NewRelicNodeJS12X:39","Version":39,"Description":"New Relic Layer for Node.js 12.x","CreatedDate":"2021-04-06T22:53:07.460+0000","CompatibleRuntimes":["nodejs12.x"],"LicenseInfo":"Apache-2.0"}}]}
```

Can you run the same and verify this URL works for you?

**Comment by BaptisteKaliop** [comment]
Somehow it works with curl since I was able to bypass the curl failure by directly setting the ARN in the code of the node_modules

**Comment by mrickard** [comment]
@BaptisteKaliop That sounds as though there's a problem resolving the region or runtime variables. If you revert your fix and log the URL, what's the value?

**Comment by BaptisteKaliop** [comment]
The same as above, I properly have the eu-west-1 configured with the proper runtime

**Comment by kolanos** [comment]
@BaptisteKaliop Did you figure this out? We haven't been able to reproduce.
