### ISSUE TITLE
Plugin does not work behind a proxy

### ISSUE THREAD

**Issue by CalMlynarczyk** [newrelic/serverless-newrelic-lambda-layers#143]
The plugin makes HTTP requests to https://api.newrelic.com/graphql in order to get the latest Lambda Layer version information. There is no way to omit this API call and instead set the Lambda Layer info yourself. If your network is behind a proxy, the plugin returns an error when trying to package a service:

```
Serverless: Plugins: ["serverless-newrelic-lambda-layers"]
 
  Fetch Error --------------------------------------------
 
  FetchError: request to https://api.newrelic.com/graphql failed, reason: read ECONNRESET
      at ClientRequest.<anonymous> (.../node_modules/node-fetch/lib/index.js:1461:11)
      at ClientRequest.emit (node:events:365:28)
      at ClientRequest.emit (node:domain:470:12)
      at TLSSocket.socketErrorListener (node:_http_client:447:9)
      at TLSSocket.emit (node:events:365:28)
      at TLSSocket.emit (node:domain:470:12)
      at emitErrorNT (node:internal/streams/destroy:193:8)
      at emitErrorCloseNT (node:internal/streams/destroy:158:3)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

I have not found a way to configure the HTTP client proxy settings. Common methods like the `HTTPS_PROXY` environment variable do not work.

**Comment by kolanos** [comment]
@CalMlynarczyk You can set the layer ARN using `layerARN` which should bypass the ARN lookup:

```
custom:
  newRelic:
    layerArn: arn:aws:lambda:us-east-1:451483290750:layer:NewRelicPython37:...
```

Let us know if that doesn't work. The plugin retrieves the latest layer ARN from `layers.newrelic-external.com`. The requests to `api.newrelic.com` are to configure the Lambda integration. This can be disabled as well, but will need to be configured manually in the New Relic UI.

**Comment by CalMlynarczyk** [comment]
@kolanos No luck, I was already specifying the layer ARN explicitly. Tried a combination of configuration settings and I don't see a way to skip the outbound HTTP requests. Below are all of the settings I am using with plugin v1.1.7 (with IDs masked):

```yml
newRelic:
  accountId: ****
  trustedAccountKey: ****
  apiKey: ****
  layerArn: arn:aws:lambda:us-east-1:451483290750:layer:NewRelicPython37:49
  disableAutoSubscription: true
  disableLicenseKeySecret: true
  enableIntegration: false # Not sure if needed
```

I see several references to the [`nergraphFetch`](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/v1.1.7/src/api.ts#L3) function, which would send these HTTP requests. [One retrieves the license key](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/2fac9343255651c0abf0a86da5c8900cb063dd04/src/index.ts#L746), which I don't believe can be skipped. The [other three references](https://github.com/newrelic/serverless-newrelic-lambda-layers/blob/2fac9343255651c0abf0a86da5c8900cb063dd04/src/integration.ts#L31) are for fetching the NR Integration information.

**Comment by kolanos** [comment]
@CalMlynarczyk Yeah, there isn't a config option to set the license key to bypass that request. We would welcome any pull request to add such functionality.

How are you handling telemetry transport? That will be over HTTP to a New Relic endpoint as well. We typically recommend configuring an internet gateway if running behind a VPC.

**Comment by CalMlynarczyk** [comment]
We don't have any issues running the telemetry behind our proxy. We have functions that both do and do not use our company's proxy. The ones that do not use the IG approach you mentioned. We configure the proxy using an environment variable `HTTPS_PROXY` on the other functions that use the New Relic layer.

I see two options to solve this: provide a configuration value that allows users to skip any outgoing HTTP requests, or add support for proxy configurations. If I were to propose a PR, I would build in the proxy support so that users behind one aren't crippled compared to typical use cases.

NodeJS HTTP client libraries have a bad history of requiring some gymnastics in order to configure proxy settings, so I'm guessing we need to expose some configuration options somewhere in order pass them to the HTTP client in the plugin code. Or we could pull in the `HTTPS_PROXY` etc. environment variables that are often used to set proxy configurations in a shell environment.
