### ISSUE TITLE
Serverless Lambda layer nodjs12x Module not found issue

### ISSUE THREAD

**Issue by ranjithgowdan123** [newrelic/serverless-newrelic-lambda-layers#154]
This is the trace I am getting in cloud watch

{
    "errorType": "Error",
    "errorMessage": "Unable to import module 'index'",
    "stack": [
        "Error: Unable to import module 'index'",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:42:13)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:64:50)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:83:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)"
    ]
}

**Comment by cristian-pelegrin** [comment]
hey @ranjithgowdan123  were you able to solve it?.

I'm having similar issue with `nodejs14.x`

```
{
    "errorType": "Error",
    "errorMessage": "Unable to import module 'dist/src/apollo-server'",
    "stack": [
        "Error: Unable to import module 'dist/src/myFunctionName'",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:42:13)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:64:50)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Module.require (internal/modules/cjs/loader.js:961:19)",
        "    at require (internal/modules/cjs/helpers.js:92:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:83:12)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)"
    ]
}

```

i'm using `serverless-webpack` plugin too, could be related that?

**Comment by mrickard** [comment]
@cristian-pelegrin This is very likely a conflict with `serverless-webpack`. We recommend that you check the order of plugins--serverless-newrelic-lambda-layers plugin must come after serverless-webpack in the plugins block of your serverless.yml file.

**Comment by alphaadidas** [comment]
had the same issue with `serverless-bundle`... changing the plugin order fixed this too.
