### ISSUE TITLE
Not able to find newRelicId from environment

### ISSUE THREAD

**Issue by varora1406** [newrelic/serverless-newrelic-lambda-layers#176]
I am trying to add NewRelic to my Node.js Application, but am unable to do it as you can see from `logs`.
I am running command - `serverless deploy` 

Logs - 
Serverless: Plugins: ["serverless-offline","serverless-newrelic-lambda-layers"]
Serverless: Adding NewRelic layer to slack
Serverless: No New Relic Account ID specified for "slack"; skipping.
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: No New Relic AWS Lambda integration found for this New Relic linked account and aws account.
Serverless: No New Relic Account ID specified; Cannot check for required NewRelicLambdaIntegrationRole.

------

serverless.yml - 
custom:
  newRelic:
    accountId: ${env:NEWRELIC_ACCOUNT_ID}
    apiKey: ${env:NEWRELIC_API_KEY}
    enableExtension: true
    enableFunctionLogs: true
    enableIntegration: true
    logEnabled: true
    logLevel: debug
    
 ---
 serverless app parameters - 
 
![image](https://user-images.githubusercontent.com/24986539/146670061-60ce1227-a9e2-4156-8f3c-0008a07cb577.png)

**Comment by mrickard** [comment]
@varora1406 This sounds like an issue related to how your serverless.yml is structured. Would you be able to share the entire (redacted) serverless.yml?
