### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by alexanderkraemer** [newrelic/serverless-newrelic-lambda-layers#178]
Is it planned to add PHP support?
As we are already able to have custom runtimes with PHP installed, it would make a lot of sense!

**Comment by mrickard** [comment]
That isn't currently on the road map, but we'd welcome community contributions. It'd require adding a serverless mode to the PHP agent, creating/publishing a PHP layer to install the agent, and then adding PHP as an option here--so it'd be at least three different repos externally, along with some internal ones.

**Comment by alexanderkraemer** [comment]
Ok, thank you for the insights!
