### ISSUE TITLE
Support for custom runtime

### ISSUE THREAD

**Issue by aniamin** [newrelic/serverless-newrelic-lambda-layers#206]
Hi,

We use newrelic for monitoring our laravel lambda functions using newrelic. Currently we use [bref](bref.sh) runtime (a custom php runtime for Lambda). Will there be any support near future for custom runtime..?

**Comment by mrickard** [comment]
@aniamin I think so--while we wouldn't be installing an agent, I'd think the custom runtimes could benefit from using the extension, if the custom runtime environment supports the extension API. I'll make a ticket for that.

**Comment by NeilJ247** [comment]
Quite keen to see this support as well.  I wanting to send logs straight to NR rather than Cloudwatch.

**Comment by navihtot** [comment]
Any update on this topic? there is already a bref extension for New Relic https://github.com/brefphp/extra-php-extensions/blob/master/docs/newrelic.md, but I was unable to make it work as agent cannot reach the daemon on lambda somehow.
In any case that would be reporting back to APM as far as I understand and not in the same fashion as other Lambda functions like serverelss node.js for example

**Comment by mrickard** [comment]
@navihtot This sounds like a feature request for us. The best way to surface this to the right teams would be to submit a feature request here: https://issues.newrelic.com/

(Closing to redirect to the NR issues pipeline.)
