### ISSUE TITLE
Support for NEW_RELIC_EXTENSION_LOGS_ENABLED

### ISSUE THREAD

**Issue by ShaunInIdaho** [newrelic/serverless-newrelic-lambda-layers#208]
The latest [newrelic-lambda-layer release](https://github.com/newrelic/newrelic-lambda-extension/releases/tag/v2.2.0) includes support for a new environment variable which allows you to disable the logs coming from the log extension itself.  This is important as more people adopt log patterns since these log messages show up on every single Lambda invocation (and are usually at the top of the log patterns).

Here's the [Pull Request](https://github.com/newrelic/newrelic-lambda-extension/pull/105).  

Support for `NEW_RELIC_EXTENSION_LOGS_ENABLED` will need to be added here to support this once the layer is updated.

**Comment by mrickard** [comment]
@ShaunInIdaho This is on deck--it should be included in an upcoming release.

**Comment by mrickard** [comment]
`enableExtensionLogs` is now available in version 3.1.0, though you can also set any environment variable as part of `provider.environment`.
