### ISSUE TITLE
Support for all Extension environment variables

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/serverless-newrelic-lambda-layers#209]
The following [list of environment variables](https://github.com/newrelic/newrelic-lambda-extension/blob/34d2ef34a8e83061da971f5db893cc686c7f70f3/config/config.go#L35-L46) can be configured for the Extension. We should ensure that each can be set via the serverless plugin.

**Comment by mrickard** [comment]
@keegoid-nr Any environment variable can simply be passed through by defining it as part of `provider.environment`. Some of those (ripe and rot values, for example) are arguably special cases that don't need to be handled through the proxy of the plugin.
