### ISSUE TITLE
Runetime error: Improperly formatted handler environment variable

### ISSUE THREAD

**Issue by deathemperor** [newrelic/serverless-newrelic-lambda-layers#218]
Serverless.yml config:

Serverless version: 3.10.2

```
custom
  newRelic:
    accountId: 34***
    apiKey: eba***
    linkedAccount: 11***
    debug: true
```

Logs
```
{
    "errorType": "Error",
    "errorMessage": "Improperly formatted handler environment variable: ./functions/index.handler",
    "stack": [
        "Error: Improperly formatted handler environment variable: ./functions/index.handler",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:27:11)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:62:50)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:186:10)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)"
    ]
}
```

**Comment by mrickard** [comment]
@deathemperor I've seen this when the handler value begins with `./` before the path. The Lambda environment assumes that the handler entry point is in `/var/task`, so you could just set it as `functions/index.handler`.

**Comment by deathemperor** [comment]
that fixed it but another issue arises

```

{
    "errorType": "Error",
    "errorMessage": "Unable to import module 'functions/graphql/order'",
    "stack": [
        "Error: Unable to import module 'functions/graphql/order'",
        "    at getHandler (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:40:13)",
        "    at Object.<anonymous> (/opt/nodejs/node_modules/newrelic-lambda-wrapper/index.js:62:50)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Module.require (internal/modules/cjs/loader.js:974:19)",
        "    at require (internal/modules/cjs/helpers.js:101:18)",
        "    at _tryRequire (/var/runtime/UserFunction.js:186:10)",
        "    at _loadUserApp (/var/runtime/UserFunction.js:197:12)"
    ]
}
```

My applications have been working fine before adding this plugin. Shouldn't this plugin cause this?

**Comment by mrickard** [comment]
@deathemperor The plugin isn't the cause here--the plugin is a deployment convenience for installing and configuring a New Relic agent. The default configuration works for most functions.

What I'm seeing here is that the NR Agent is trying to wrap dependencies it can't find. I would expect that if some of your require or import statements were defined with pathways like `./functions/directory/file`. While your function code is in `/var/task`, layer-installed dependencies are at `/opt/nodejs/...`. Without the `./`, the agent relies on the Lambda environment path, and would check both `/opt/nodejs` and `/var/task`, but with the preceding dot-slash, it's going to look for the dependency in its directory only.  Do some of your import or require statements begin with `./` characters?

**Comment by deathemperor** [comment]
Many imports in our source codes use `./`. Refactoring codes from using `./` import is not an option for us because we're still testing if New Relic fits our use cases.

**Comment by mrickard** [comment]
@deathemperor If you'd like to avoid refactoring, you should be able to, but that solution requires a bit of manual work. 

1. Make a note of the various environment variables the plugin writes, and include them in the `provider.environment` of your function's serverless.yml. 
2. Include the ARN of the Lambda layer that the plugin configures (or include newrelic as a dependency)
3. Remove the plugin from your serverless.yml and your package.json
4. Follow the instrumentation instructions for Node here: https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/
