### ISSUE TITLE
serverless-newrelic-lambda-layers breaks other layers

### ISSUE THREAD

**Issue by Shereef** [newrelic/serverless-newrelic-lambda-layers#242]
Here is a repo where you can reproduce the issue  the issue https://github.com/Shereef/nr-lambda-issue

Whenever I enable the serverless-newrelic-lambda-layers it removes the other layers

The reason behind this is that the new relic uses per function layers which override service/provider level layers

**Comment by Shereef** [comment]
I have also opened a support Case #00040541

**Comment by mrickard** [comment]
@Shereef Thank you again! (Release 3.2.0 is in process.)
