### ISSUE TITLE
Trace ID not propagating

### ISSUE THREAD

**Issue by rafapaulin** [newrelic/serverless-newrelic-lambda-layers#268]
I am trying to test the distributed tracing ID using this serverless plugin.

It works okay when different lambda functions invoke each other on the sale `.ts` file. But when I try to invoke another lambda from a lambda function, either through AWS SDK or through an http endpoint, the new relic's log entry gets a different `trace.id`

Is there a way to pass the same trace ID to the called lambdas?

(I am also using [winston log enricher](https://github.com/newrelic/newrelic-winston-logenricher-node))

**Comment by rafapaulin** [comment]
I could forward the parent trace id to the child through attributes, but I am also do not know how to get the current trace id from my lambda function. Is there a way to do that?

**Comment by mrickard** [comment]
@rafapaulin I have an example of how to do this in a comment on this issue: https://github.com/newrelic/serverless-newrelic-lambda-layers/issues/264

**Comment by mrickard** [comment]
@rafapaulin You shouldn't have to include the New Relic agent in your deployed code if it's installed via the Lambda Layer. If you're running into trouble in your local dev environment if you don't have it in your package.json, then you could add it locally as one of your devDependencies. That way your local environment will have a local `newrelic` agent, and your deployed function will find the agent installed via the layer.
