### ISSUE TITLE
Update fs-extra to newer version

### ISSUE THREAD

**Issue by djordje-stevanovic-daysmart** [newrelic/serverless-newrelic-lambda-layers#348]
Hello, we are using this package in our projects. Currently, dependabot tried to update the fs-extra package that is used in our project to a newer version (11.1.1), but we got a dependency tree error because serverless-newrelic-lambda-layers is using an older one (10.0.1).  Can you maybe update fs-extra  that is used as a peer dependency in this project to a newer version?

**Comment by jordigh** [comment]
How about just removing the dependency instead?

**Comment by djordje-stevanovic-daysmart** [comment]
Thank you!
