### ISSUE TITLE
Support python3.10 in serverless plugin

### ISSUE THREAD

**Issue by chistyakov** [newrelic/serverless-newrelic-lambda-layers#354]
AWS Lambda adds support for Python 3.10

https://aws.amazon.com/about-aws/whats-new/2023/04/aws-lambda-python-3-10/

Could you please release NewRelic layer for this runtime.

**Comment by mrickard** [comment]
@chistyakov Version 3.5.0 supports Python 3.10 layers, and those layers should be available in all regions.

**Comment by chistyakov** [comment]
Thank you!

**Comment by chistyakov** [comment]
Could you please also update list of supported runtimes in the README.md
https://github.com/newrelic/serverless-newrelic-lambda-layers#supported-runtimes
