### ISSUE TITLE
Issue with loading of ES modules from plugin layer higher than 30

### ISSUE THREAD

**Issue by srdjan-drca** [newrelic/serverless-newrelic-lambda-layers#358]
Hello,

In one lambda service I am using version 3.4.3 of this plugin. In other I am using version 3.5.0 (latest). Both services are using NodeJs inside AWS. Independent of plugin version if layer version is:
`arn:aws:lambda:${self:custom.config.DSI_AWS_REGION}:451483290750:layer:NewRelicNodeJS18X:31` or
`arn:aws:lambda:${self:custom.config.DSI_AWS_REGION}:451483290750:layer:NewRelicNodeJS18X:32` I am seeing error when my module needs to be imported from new relic plugin. Seams that something from layer of this plugin is trying to import ES module using require. It is working fine with version 30 and lower.
![2023-07-03 17_32_13-Window](https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/19403439/d8f34b1e-fb12-4b06-b5f9-3dce26d68ac8)

Could you take a look what is the problem? Thank you.

**Comment by nthornton2010** [comment]
According to a paragraph in the link below, you must set the NEW_RELIC_USE_ESM environment variable to true in the Lambda for the Layer to work with ES Modules. The serverless plugin's code should be updated to support setting this as a config option. Right now we're setting it directly in the environment variables area which is disconnected from the rest of the config for the layer.

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/troubleshooting/troubleshoot-enabling-serverless-monitoring-aws-lambda/

This is what the documentation I'm referring to in the above link:
`If you're using ES Modules with a Node.js function, make sure that the environment variable NEW_RELIC_USE_ESM is set to true. Additionally, make sure you're using async/await or promises for handling asynchronous behavior in your function, as callback-based functions are not supported when using ES Modules.`

**Comment by mrickard** [comment]
@srdjan-drca We've released a new version of the wrapper in Node Lambda layers, which improves performance. Please try updating to the latest version.
