### ISSUE TITLE
Support python3.11 in serverless plugin 

### ISSUE THREAD

**Issue by chistyakov** [newrelic/serverless-newrelic-lambda-layers#373]
AWS Lambda adds support for Python 3.11

https://aws.amazon.com/about-aws/whats-new/2023/07/aws-lambda-python-3-11/

Could you please
* release NewRelic layer for this runtime
* mention python3.10 and python3.11 in readme https://github.com/newrelic/serverless-newrelic-lambda-layers#supported-runtimes

**Comment by umaannamalai** [comment]
Thank you for opening this issue @chistyakov! This is being worked on currently and we will provide you with an update once the 3.11 layers are released.

**Comment by umaannamalai** [comment]
Hi @chistyakov - we have released Python 3.11 lambda layers: https://layers.newrelic-external.com/. The README on this repo has been updated to reflect currently supported runtimes and we will be doing a full release of the serverless plugin in the next two weeks.

**Comment by chistyakov** [comment]
thank you!
