### ISSUE TITLE
Agent version out of date (Node.js 18.x, ARM64)

### ISSUE THREAD

**Issue by mu29** [newrelic/serverless-newrelic-lambda-layers#374]
I'm using the `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS18XARM64:40` layer for my Lambda function, which is running on Node.js 18.x / ARM64 architecture.

<img width="1182" alt="Screenshot 2023-08-14 at 12 13 58 AM" src="https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/8934513/c48cc8f9-dc2d-4bf9-abfa-5eff5169ab48">

Even though it is the latest image, it is not forwarding any logs to my New Relic Dashboard.

<img width="994" alt="Screenshot 2023-08-12 at 12 28 56 PM" src="https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/8934513/90f4b379-405b-431e-98f6-5e8cf3630260">

Did I miss something?

**Comment by mrickard** [comment]
@mu29 I've just verified that the agent distributed with the latest layer (in this case, `arn:aws:lambda:us-east-1:451483290750:layer:NewRelicNodeJS18XARM64:40`for you) is in fact `v10.6.2`. 

If you're seeing the out-of-date message, one of these two scenarios is likely:
- You're using a different layer version than you expect. Check the ARN of the layer version in your AWS UI.
- You've *also* included a version of the `newrelic` agent in your deployment package. Even if you apply the layer, this deployed version would be used first. We recommend *not* including the agent as part of the deployment package.

(One caveat about that last piece of advice is for people using ESM in Node 14 or Node 16, which can't use the layer-installed instrumentation. But you're on Node 18.)
