### ISSUE TITLE
Need Hotfix Release of Recent Change

### ISSUE THREAD

**Issue by kevingilbert100** [newrelic/serverless-newrelic-lambda-layers#380]
[serverless-newrelic-lambda-layers](https://github.com/newrelic/serverless-newrelic-lambda-layers/pull/379)

Can we cut a release of this recent change? This is blocking our flow

**Comment by kevingilbert100** [comment]
@bizob2828

**Comment by mrickard** [comment]
@kevingilbert100 v4.0.0 is now released.
