### ISSUE TITLE
Plugin not found v5.2.0

### ISSUE THREAD

**Issue by lukehedger** [newrelic/serverless-newrelic-lambda-layers#448]
Receiving the following error after upgrading from v5.1.0 to v5.2.0:

> Serverless plugin "serverless-newrelic-lambda-layers" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-newrelic-lambda-layers" to install it.

Any ideas why this would happen? No other changes made to the serverless.yml.

**Comment by bizob2828** [comment]
@lukehedger might be related to #449. Can you try again we released 5.2.1

**Comment by lukehedger** [comment]
Thanks @bizob2828
