### ISSUE TITLE
Release 5.2.0 failed to be published on NPM

### ISSUE THREAD

**Issue by ezfepo** [newrelic/serverless-newrelic-lambda-layers#449]
Hello,

Last release 5.2.0 is failed to be published on NPM

Yesterday NPM suffer a small incident, and it seems that at least v5.2.0 package released has been affected.

https://status.npmjs.org/
![image](https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/20102608/11432235-50ed-46b0-a463-346120a4abb2)

As you can see dist folder is missing.

https://www.npmjs.com/package/serverless-newrelic-lambda-layers/v/5.2.0?activeTab=code
![image](https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/20102608/82a7b99b-cb6d-453f-87d7-4511df5e20aa)

So, whenever we try to install the package, the missing dist folder is not available.

![image](https://github.com/newrelic/serverless-newrelic-lambda-layers/assets/20102608/2f55d4e8-6dbe-4c28-b422-7457f3df776c)

It would be great if you can re-publish the package on npm.

Thanks

**Comment by bizob2828** [comment]
@chaudharysaket this is probably because this project is now using the reusable workflow our team maintained. It doesn't do a `npm run build` before publishing which appears to be needed for this project
