### ISSUE TITLE
Is it possible to access NR agent with dynamic wrapping?

### ISSUE THREAD

**Issue by Noor0** [newrelic/serverless-newrelic-lambda-layers#459]
I want to use `recordMetric` and `recordEvent` for custom instrumentation but it's not mentioned in the docs. How can I access the NewRelic agent to access these methods?

**Comment by chaudharysaket** [comment]
Hi @Noor0 
You can use serverless plugin for  Node.js, Python and Java runtimes 
You can use the New Relic language agents way to record custom events and metrics. 
For python, you can refer to an example [here](https://github.com/newrelic/newrelic-lambda-extension/blob/main/examples/sam/python/newrelic_example_python/app.py)
```
# This is an example of a custom event. `FROM MyPythonEvent SELECT *` in New Relic will find this event.
    agent.record_custom_event("MyPythonEvent", {
        "zip": "zap"
    })
    # This attribute gets added to the normal AwsLambdaInvocation event
    agent.add_custom_attribute('customAttribute', 'customAttributeValue')
```
Please let us know if you still face any issue. Thank you

**Comment by Noor0** [comment]
I'm using this package already in Node, I'm wondering if I have to install the newrelic package and initialize agent to record custom metrics or is there a way to access the agent from the `serverless-newrelic-lambda-layers` plugin?

**Comment by chaudharysaket** [comment]
Hi @Noor0 
You don't need to install the newrelic package as the `serverless-newrelic-lambda-layers` plugin installs the relevant New Relic lambda layer. You can use the following sample lambda runtime code, if you are using ES modules (ECMAScript)
```
import newrelic from 'newrelic';

export const handler = async (event) => {
  newrelic.recordMetric('Cart/ChargeAmount', 3);
  newrelic.recordCustomEvent('WidgetSale', { color: 'red', weight: 12.5 });
  
  const response = {
    statusCode: 200,
    body: JSON.stringify('Hello from Lambda!'),
  };
  return response;
};
```
Reference docs:
- Nodejs [recordCustomEvent](https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/apm-report-custom-events-attributes/#node-att)
- Nodejs [recordMetric](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-metrics/)
Please let us know if you still face any issue. Thank you!

**Comment by chaudharysaket** [comment]
Please re-open, if you still face the issue. Thank you!
