### ISSUE TITLE
Serverless V4 Support

### ISSUE THREAD

**Issue by denisegiubilei** [newrelic/serverless-newrelic-lambda-layers#461]
It appears that the plugin is not compatible with Serverless v4. Is there a possibility that support will be added in the near future? Thank you.

**Comment by chaudharysaket** [comment]
We are looking into the issue. Thank you for raising it.

**Comment by chaudharysaket** [comment]
Hi @denisegiubilei 
I tested it with serverless v4 and the plugin is compatible, with my testing. Could you please share error logs when using plugin with serverless v4.
Thank you!

**Comment by chaudharysaket** [comment]
We are re-looking at the issue in #467
