### ISSUE TITLE
The problem with the latest (v16) layer ARN for Python 3.6

### ISSUE THREAD

**Issue by aandrusyk-amplify** [newrelic/serverless-newrelic-lambda-layers#58]
The plugin has stopped working properly after the latest layer ARN `arn:aws:lambda:us-west-2:451483290750:layer:NewRelicPython36:16`
was released. Please check.

**Comment by kolanos** [comment]
@aandrusyk-amplify Thanks for reporting. Any more details as to what is not working?

**Comment by kolanos** [comment]
@aandrusyk-amplify There's been a couple layer releases since v16, are you still having issues with the latest layer version?

**Comment by aandrusyk-amplify** [comment]
Versions v16, v17, v18 are not working for me. The last working version is v15.

The Summary page for Lambda functions doesn't present information like duration, invocations, and others. However, CloudWatch metrics page does.

**Comment by aandrusyk-amplify** [comment]
The newest v19 works again.
You may close the issue. 
Thank you!

**Comment by kolanos** [comment]
@aandrusyk-amplify Thanks for letting us know.
