### ISSUE TITLE
Problem with the region in serverless.yml

### ISSUE THREAD

**Issue by kelvinatorHK** [newrelic/serverless-newrelic-lambda-layers#78]
Came across a problem when we upgrade the library from 0.1.x to 0.2.x
SyntaxError: Unexpected token u in JSON at position 0
       at JSON.parse (<anonymous>)
       at request.then.response (/builds/ns-am/product-recommendation/product-recommendation-analytics-integration/node_modules/serverless-newrelic-lambda-layers/dist/index.js:264:38)

Basically, our serverless.yml with the region like the following:
**region: ${opt:region, 'us-west-2'}**

When we tried to dig into the code more, it seems that the region is set in the constructor (0.2x).   Thus, the region will not be replaced by serverless int time.  When it is calling getLayerArn(), the region is still ${opt:region, 'us-west-2'}.   

Thanks for your time!

**Comment by mrickard** [comment]
@kelvinatorHK Thank you for the report! The json parsing issue is separate; we have a fix that'll be released soon--very likely in the next hour. This may also resolve the region issue, but we'll look into it.

**Comment by kelvinatorHK** [comment]
Thanks the reply.   We have tried v0.2.5, but it still does not work.    Basically, if you are using serverless variable for the provider.region in the serverless.yml, it will fail:
  RequestError: Error: Invalid URI "https:///$%7Bopt:region,%20%27us-west-2%27%7D.layers.newrelic-external.com/get-layers?CompatibleRuntime=nodejs10.x"

Sample YAML
provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-west-2'}

**Comment by mrickard** [comment]
@kelvinatorHK Thanks! That's curious--I did a local test with a CLI option variable for region, and it behaved as expected. That is, with 
```
provider:
  name: aws
  runtime: nodejs12.x
  timeout: 6
  region: ${opt:region, 'us-east-1'}
...etc
```
in the serverless.yml, and deploying with 
```
sls deploy -v -l --region us-east-2
```
I didn't get any errors, and had a successful deployment to us-east-2 instead of us-east-1. 

Would you be able to share these? 
* OS and version
* serverless version
* a sanitized version of your serverless.yml (no account IDs or secrets)
* package.json

**Comment by kelvinatorHK** [comment]
@mrickard Thanks for your prompt response.

We used a CI/CD pipeline to do our sls deploy (using gitlab runner - a docker image).  When we saw the problem after upgrading to 0.2.4, I tested it out on my box.

**It seems that the '--region region' does the trick for v0.2.5.  (When I tested 0.2.5 out on my box, I did not put it the --region flag)**

Here is different scenario I have tried:
v0.1.20
#sls deploy     (it works!!!)
#sls deploy --region us-west-2 (it works!!!)

v0.2.4
#sls deploy       (error)
#sls deploy --region us-west-2 (error)

**v0.2.5
#sls deploy        (error)
#sls deploy  --region us-west-2 (it works!!!)**  


Thanks so much for your help

Here

**Comment by kelvinatorHK** [comment]
OS and version:  MacOS Mojave 10.14.6
serverless version: 1.80.0
serverless.yml:
`
service: xxxxxxxxxxx

provider:
  name: aws
  runtime: nodejs10.x
  endpointType: regional
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 300
  logRetentionInDays: 14
  tracing: true
  basePath: 'xxxxxxxxxx'
  environment:
     deploymentBucket:
    name: xxxxxxxx

  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:PutItem
        - dynamodb:BatchWriteItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "xxxxxxxxxxx"
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:ssm"
            - Ref: "AWS::Region"
            - Ref: "AWS::AccountId"
            - xxxxxx
functions:
  queryRelatedProductsAnalytics:
    handler: src/index.handler
    reservedConcurrency: 1
    events:
      - schedule:
          name: xxxxxxxxx
          description: Once per month, triggers a query of the product analytics database for new recommendations
          rate: cron(17 2 3 * ? *)
          enabled: true

#CI/CD Deployment configuration update with caution
custom:
  ##Used so servless-offline has the same path as after deploying to the gateway
  serverless-offline:
    prefix: ${self:provider.basePath}
  ## newRelic instrumentation
  newRelic:
    accountId: ${ssm:/global/newRelicAccountId}
  ###Used for Assigning Function to Custom API Domain
  customDomain:
    basePath: ${self:provider.basePath}
    domainName: ${ssm:/global/apidomain}
    stage: ${self:provider.stage}
    certificateName: 'xxxxxxxxxx'
    endpointType: 'regional'
    createRoute53Record: false
  dynamodb:
    stages:
      - dev
    start:
      migrate: true
  endpoints:
    dynamodb-url: 'http://localhost:8000'
    lambda-url: 'http://localhost:3000'
 
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-tracing
  - serverless-plugin-bind-deployment-id
  - serverless-pseudo-parameters
  - serverless-newrelic-lambda-layers

`
package.json
    "name": "xxxxxxxx",
    "description": "xxxxxxx",
    "version": "1.0.0",
    "private": true,
    "scripts": {
        "dev": "serverless offline",
        "test": "nyc mocha",
        "lint": "eslint src/**/*.js"
    },
    "dependencies": {
        "@google-cloud/bigquery": "5.2.0",
        "aws-xray-sdk-core": "2",
        "config": "3",
        "uuid": "8.3.0"
    },
    "devDependencies": {
        "@types/aws-lambda": "8.10.62",
        "aws-sdk": "2.748.0",
        "aws-sdk-mock": "5.1.0",
        "chai": "4.2.0",
        "eslint": "7.8.1",
        "eslint-config-google": "0",
        "eslint-plugin-json": "1",
        "mocha": "6",
        "mochawesome": "4",
        "nyc": "14",
        "redoc-cli": "0.9.12",
        "serverless": "1.82.0",
        "serverless-domain-manager": "3.3.2",
        "serverless-dynamodb-local": "0.2.39",
        "serverless-newrelic-lambda-layers": "0.2.5",
        "serverless-offline": "6.5.0",
        "serverless-plugin-bind-deployment-id": "1.2.0",
        "serverless-plugin-tracing": "2.0.0",
        "serverless-prune-plugin": "1.4.3",
        "serverless-pseudo-parameters": "2",
        "sinon": "7",
        "sinon-chai": "3.5.0"
    }
}
`
`

**Comment by mrickard** [comment]
@kelvinatorHK Great--glad to help! It does look like the region option in the deploy command was the answer there.

**Comment by mrickard** [comment]
Closing issue; the plugin doesn't interfere with Serverless command-line options in the .yml.

**Comment by nonix911** [comment]
Yes, but it's not required. Need to update docs or smting else. Anyway if will be the same value like ${opt:region, **'us-west-2'}** to change on the **us-west-2**. Does it make sense?
