### ISSUE TITLE
Is there a way to use this without adding the layer?

### ISSUE THREAD

**Issue by david-a-jetter** [newrelic/serverless-newrelic-lambda-layers#79]
I get the irony of the question vs. the name of the plugin, but given that there are a limited number of layers that can be provided per Lambda, it would be a nice option to be able to leverage the plugin for all of the niceties it provides while opting to supply the NewRelic SDK as standard NPM or PIP package.

I know Python Serverless apps can leverage the `serverless-python-requirements` plugin to neatly handling PIP/Poetry installed packages, and I imagine there are similar capabilities for NodeJS Serverless apps. However, this `serverless-newrelic-lambda-layers` plugin simplifies a lot of the deployment concerns around log group subscriptions that should be able to be accomplished without the addition of the layer itself.

A config option for something like `skipLayerAddition` that defaults to `false` would be a nice enhancement.

**Comment by kolanos** [comment]
david-a-jetter Thanks for the question. Recommend checking out the [newrelic-lambda-cli](https://github.com/newrelic/newrelic-lambda-cli) which breaks these steps into separate commands. You can just skip the `newrelic-lambda layers install` command in this case.
