### ISSUE TITLE
Time for a Changelog

### ISSUE THREAD

**Issue by Ephesoft-Stitus** [newrelic/serverless-newrelic-lambda-layers#89]
With this project currently in pre-release [semantic versioning](https://semver.org/) its expected for breaking changes to happen without a major version bump.  The challenge for consumers of the package is that you are unaware if there are any breaking changes and it makes for a difficult decision on whether or not to update the package.

If there were a change log that called out breaking changes (vs bug fixes and feature updates) it would really simplify the process of determining whether or not the package should be updated on our projects.

If you're new to change logs it is very simple and you can get started by going to [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

Anyone coming up from version 0.1.x for example will need to make some changes to their serverless file.

**Comment by kolanos** [comment]
@Ephesoft-Stitus Thanks for the suggestion. We do include a list of changes in our releases:

https://github.com/newrelic/serverless-newrelic-lambda-layers/releases

Including highlighting breaking changes. Is there anything there we can improve upon?

**Comment by Ephesoft-Stitus** [comment]
@kolanos - That is great.  I'm used to seeing CHANGELOG.md at the root but the releases works just as well, if not better.
