### ISSUE TITLE
Does this plugin support container backed Lambdas?

### ISSUE THREAD

**Issue by joshburt** [newrelic/serverless-newrelic-lambda-layers#97]
AWS recently released support for container backed lambdas.  While serverless is able to deploy the solution with the plugin 'serverless-newrelic-lambda-layers' present, I do not see any indication that this is actually working.

With our normal lambdas this work seamlessly, however this seems to handle the situation different.

Steps to reproduce:
1. Create a serverless lambda definition.
2. Ensure it is configured to use a container:

> functions:
>   SomeFunction:
>    name: SomeFunction
>     image: {AWS ACCOUNT NUMBER}.dkr.ecr.{AWS REGION}.amazonaws.com/{ECR REGISTRY NAME}@{IMAGE DIGEST}

3. Enable the plugin
4. Deploy

At this point invocations do not seem to indicate new relic is present, and information is not reported to New Relic for the container backed lambda.

**Comment by kolanos** [comment]
@joshburt No, this plugin does not currently support container backed functions.

**Comment by kolanos** [comment]
@joshburt For now, you'll need to look at manual instrumentation for container backed functions. More details on manual instrumentation [here](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda#manual-connect-to-aws). You can likely bake most of these steps into a `Dockerfile` or equivalent. You could also pull pieces from our [layers](https://github.com/newrelic/newrelic-lambda-layers), depending on which runtime you're using.

**Comment by joshburt** [comment]
Beautiful!  This is all I needed to know.  Thanks so much for the quick response!
